### ISSUE TITLE
not working for nokia 6.1 2018

### ISSUE THREAD

**Issue by flowser** [RaghuVarma331/Nokia-Tool#1]
not working for nokia 6.1 2018

**Comment by RaghuVarma331** [comment]
get me log.txt

**Comment by flowser** [comment]
after flashing with the two roms i get " cannot load android system. your data may be corrupt. if you continue to get this message, you may need to perfomr a factory reset and erase all user data stored on this device.             its not booting at all, is there a way to install the original firmware?

**Comment by flowser** [comment]
i read this 
fastboot getvar all
(bootloader) is-special-psn:no
(bootloader) parallel-download-flash:yes
(bootloader) hw-revision:10000
(bootloader) unlocked:no
(bootloader) off-mode-charge:1
(bootloader) charger-screen-enabled:1
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4009
(bootloader) version-baseband:
(bootloader) version-bootloader:
(bootloader) erase-block-size: 0x200
(bootloader) logical-block-size: 0x200
(bootloader) variant:SDM EMMC
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0x507BFBE00
(bootloader) partition-type:vendor_b:raw
(bootloader) partition-size:vendor_b: 0x40000000
(bootloader) partition-type:vendor_a:raw
(bootloader) partition-size:vendor_a: 0x40000000
(bootloader) partition-type:system_b:ext4
(bootloader) partition-size:system_b: 0xC0000000
(bootloader) partition-type:system_a:ext4
(bootloader) partition-size:system_a: 0xC0000000
(bootloader) partition-type:sti:raw
(bootloader) partition-size:sti: 0x200000
(bootloader) partition-type:logdump:raw
(bootloader) partition-size:logdump: 0x4000000
(bootloader) partition-type:frp:raw
(bootloader) partition-size:frp: 0x80000
(bootloader) partition-type:keystore:raw
(bootloader) partition-size:keystore: 0x80000
(bootloader) partition-type:ssd:raw
(bootloader) partition-size:ssd: 0x2000
(bootloader) partition-type:logfs:raw
(bootloader) partition-size:logfs: 0x800000
(bootloader) partition-type:misc:raw
(bootloader) partition-size:misc: 0x100000
(bootloader) partition-type:persist:raw
(bootloader) partition-size:persist: 0x2000000
(bootloader) partition-type:reserved_bak:raw
(bootloader) partition-size:reserved_bak: 0x1000000
(bootloader) partition-type:elabel:raw
(bootloader) partition-size:elabel: 0x1000000
(bootloader) partition-type:splash2:raw
(bootloader) partition-size:splash2: 0x2400000
(bootloader) partition-type:splash_b:raw
(bootloader) partition-size:splash_b: 0x2400000
(bootloader) partition-type:splash_a:raw
(bootloader) partition-size:splash_a: 0x2400000
(bootloader) partition-type:cda_b:raw
(bootloader) partition-size:cda_b: 0x800000
(bootloader) partition-type:cda_a:raw
(bootloader) partition-size:cda_a: 0x800000
(bootloader) partition-type:hidden_b:raw
(bootloader) partition-size:hidden_b: 0x2800000
(bootloader) partition-type:hidden_a:raw
(bootloader) partition-size:hidden_a: 0x2800000
(bootloader) partition-type:systeminfo_b:ext4
(bootloader) partition-size:systeminfo_b: 0x40000
(bootloader) partition-type:systeminfo_a:ext4
(bootloader) partition-size:systeminfo_a: 0x40000
(bootloader) partition-type:sutinfo:raw
(bootloader) partition-size:sutinfo: 0x400
(bootloader) partition-type:nvdef_b:raw
(bootloader) partition-size:nvdef_b: 0x400000
(bootloader) partition-type:nvdef_a:raw
(bootloader) partition-size:nvdef_a: 0x400000
(bootloader) partition-type:nvcust:raw
(bootloader) partition-size:nvcust: 0x200000
(bootloader) partition-type:hwcfg:raw
(bootloader) partition-size:hwcfg: 0x100000
(bootloader) partition-type:box:raw
(bootloader) partition-size:box: 0x800000
(bootloader) partition-type:logbk:raw
(bootloader) partition-size:logbk: 0x4000000
(bootloader) partition-type:reserved:raw
(bootloader) partition-size:reserved: 0x1000000
(bootloader) partition-type:boot_b:raw
(bootloader) partition-size:boot_b: 0x4000000
(bootloader) partition-type:boot_a:raw
(bootloader) partition-size:boot_a: 0x4000000
(bootloader) partition-type:devcfg_b:raw
(bootloader) partition-size:devcfg_b: 0x100000
(bootloader) partition-type:devcfg_a:raw
(bootloader) partition-size:devcfg_a: 0x100000
(bootloader) partition-type:vbmeta_b:raw
(bootloader) partition-size:vbmeta_b: 0x10000
(bootloader) partition-type:vbmeta_a:raw
(bootloader) partition-size:vbmeta_a: 0x10000
(bootloader) partition-type:battprof:raw
(bootloader) partition-size:battprof: 0x1400000
(bootloader) partition-type:ddr:raw
(bootloader) partition-size:ddr: 0x100000
(bootloader) partition-type:storsec:raw
(bootloader) partition-size:storsec: 0x20000
(bootloader) partition-type:sec:raw
(bootloader) partition-size:sec: 0x4000
(bootloader) partition-type:toolsfv:raw
(bootloader) partition-size:toolsfv: 0x100000
(bootloader) partition-type:limits:raw
(bootloader) partition-size:limits: 0x1000
(bootloader) partition-type:dpo:raw
(bootloader) partition-size:dpo: 0x400
(bootloader) partition-type:msadp:raw
(bootloader) partition-size:msadp: 0x40000
(bootloader) partition-type:apdp:raw
(bootloader) partition-size:apdp: 0x40000
(bootloader) partition-type:dip:raw
(bootloader) partition-size:dip: 0x100000
(bootloader) partition-type:mdtp_b:raw
(bootloader) partition-size:mdtp_b: 0x2000000
(bootloader) partition-type:mdtp_a:raw
(bootloader) partition-size:mdtp_a: 0x2000000
(bootloader) partition-type:devinfo:raw
(bootloader) partition-size:devinfo: 0x1000
(bootloader) partition-type:bluetooth_b:raw
(bootloader) partition-size:bluetooth_b: 0x100000
(bootloader) partition-type:bluetooth_a:raw
(bootloader) partition-size:bluetooth_a: 0x100000
(bootloader) partition-type:abl_b:raw
(bootloader) partition-size:abl_b: 0x100000
(bootloader) partition-type:abl_a:raw
(bootloader) partition-size:abl_a: 0x100000
(bootloader) partition-type:dsp_b:raw
(bootloader) partition-size:dsp_b: 0x1000000
(bootloader) partition-type:dsp_a:raw
(bootloader) partition-size:dsp_a: 0x1000000
(bootloader) partition-type:mdtpsecapp_b:raw
(bootloader) partition-size:mdtpsecapp_b: 0x400000
(bootloader) partition-type:mdtpsecapp_a:raw
(bootloader) partition-size:mdtpsecapp_a: 0x400000
(bootloader) partition-type:cmnlib64_b:raw
(bootloader) partition-size:cmnlib64_b: 0x100000
(bootloader) partition-type:cmnlib_b:raw
(bootloader) partition-size:cmnlib_b: 0x100000
(bootloader) partition-type:cmnlib64_a:raw
(bootloader) partition-size:cmnlib64_a: 0x100000
(bootloader) partition-type:cmnlib_a:raw
(bootloader) partition-size:cmnlib_a: 0x100000
(bootloader) partition-type:keymaster_b:raw
(bootloader) partition-size:keymaster_b: 0x100000
(bootloader) partition-type:keymaster_a:raw
(bootloader) partition-size:keymaster_a: 0x100000
(bootloader) partition-type:pmic_b:raw
(bootloader) partition-size:pmic_b: 0x80000
(bootloader) partition-type:pmic_a:raw
(bootloader) partition-size:pmic_a: 0x80000
(bootloader) partition-type:hyp_b:raw
(bootloader) partition-size:hyp_b: 0x80000
(bootloader) partition-type:hyp_a:raw
(bootloader) partition-size:hyp_a: 0x80000
(bootloader) partition-type:rpm_b:raw
(bootloader) partition-size:rpm_b: 0x80000
(bootloader) partition-type:rpm_a:raw
(bootloader) partition-size:rpm_a: 0x80000
(bootloader) partition-type:tz_b:raw
(bootloader) partition-size:tz_b: 0x400000
(bootloader) partition-type:tz_a:raw
(bootloader) partition-size:tz_a: 0x400000
(bootloader) partition-type:xbl_b:raw
(bootloader) partition-size:xbl_b: 0x380000
(bootloader) partition-type:xbl_a:raw
(bootloader) partition-size:xbl_a: 0x380000
(bootloader) partition-type:modem_b:raw
(bootloader) partition-size:modem_b: 0x6E00000
(bootloader) partition-type:modem_a:raw
(bootloader) partition-size:modem_a: 0x6E00000
(bootloader) partition-type:fsg:raw
(bootloader) partition-size:fsg: 0x200000
(bootloader) partition-type:fsc:raw
(bootloader) partition-size:fsc: 0x400
(bootloader) partition-type:deviceinfo:raw
(bootloader) partition-size:deviceinfo: 0x100000
(bootloader) partition-type:securefs:raw
(bootloader) partition-size:securefs: 0x1000000
(bootloader) partition-type:rf_nv:raw
(bootloader) partition-size:rf_nv: 0x200000
(bootloader) partition-type:bspdata:raw
(bootloader) partition-size:bspdata: 0x100000
(bootloader) partition-type:modemst2:raw
(bootloader) partition-size:modemst2: 0x200000
(bootloader) partition-type:modemst1:raw
(bootloader) partition-size:modemst1: 0x200000
(bootloader) has-slot:modem:yes
(bootloader) has-slot:system:yes
(bootloader) current-slot:a
(bootloader) has-slot:boot:yes
(bootloader) slot-retry-count:b:5
(bootloader) slot-unbootable:b:no
(bootloader) slot-successful:b:yes
(bootloader) slot-retry-count:a:3
(bootloader) slot-unbootable:a:no
(bootloader) slot-successful:a:no
(bootloader) slot-count:2
(bootloader) slot-suffixes:_a,_b,
(bootloader) secure:yes
(bootloader) serialno:PL2GAR98C0301565
(bootloader) product:B2N
(bootloader) max-download-size:0x18000000
(bootloader) kernel:uefi
(bootloader) version:0.0
all:
Finished. Total time: 0.291s
